<?php

/**
 * Implements hook_entity_form_alter().
 */
function degree_admin_locks_university_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
    \Drupal::messenger()->addMessage('HOOK de degree_admin_locks_university_entity_form_alter');
    //dump($form_state);
    // Verificamos que estamos en el formulario de edición de una entidad de tipo carrera.
  if ($form_id === 'node_carrera_edit_form') {
    // Obtener el nodo actual que se está editando.
    $node = $form_state->getFormObject()->getEntity();

    \Drupal::messenger()->addMessage('HOOK de degree_admin_locks_university_entity_form_alter222');

    // Solo aplicamos esto si el campo de universidad está presente en el formulario.
    if (isset($form['field_universidad'])) {
        
      // Obtener el usuario actual.
      $current_user = \Drupal::currentUser();
      $user_id = $current_user->id();

      // Obtener el grupo asociado a esta carrera.
      $group_memberships = \Drupal::service('group.membership_loader')->loadByUser($current_user);
     
      foreach ($group_memberships as $membership) {
        
        
        $group = $membership->getGroup();
        \Drupal::messenger()->addMessage('HOOK29384kjklj ' . $group->getEntityTypeId() );
        // Verificar que el grupo esté relacionado con la universidad de la carrera actual.
        if (($group->getEntityTypeId() === 'node' || $group->getEntityTypeId() === 'group' ) && $group->getGroupType()->id() === 'universitytypegroup') {
       
          // Verificar si el usuario tiene el rol de Degree Admin dentro de este grupo.
          //\Drupal::messenger()->addMessage('HOOK ' . print_r($membership));
          $roles = $membership->getRoles();
          foreach ($roles as $role) {
            if ($role->id() === 'universitytypegroup-degree_admin') {
              // Desactivar el campo de universidad para Degree Admin.
              $form['field_universidad']['#disabled'] = TRUE;
              \Drupal::messenger()->addMessage('El campo Universidad está desactivado para Degree Admin.');
              break 2; // Salir de ambos bucles.
            }
          }
            /*
            $form['field_universidad']['widget'][0]['target_id']['#default_value'] = $entity;
            $form['field_universidad']['widget'][0]['target_id']['#options'] = [$entity->id() => $entity->label()];
            $form['field_universidad']['widget'][0]['target_id']['#disabled'] = TRUE;
            */

          
        }
      }
    }
  }

  if ($form_id === 'node_asignatura_edit_form') {
    // Obtener el nodo actual que se está editando.
    $node = $form_state->getFormObject()->getEntity();

    \Drupal::messenger()->addMessage('HOOK de degree_admin_locks_university_entity_form_alter222');

    // Solo aplicamos esto si el campo de universidad está presente en el formulario.
    if (isset($form['field_carrera'])) {
        
      // Obtener el usuario actual.
      $current_user = \Drupal::currentUser();
      $user_id = $current_user->id();

      // Obtener el grupo asociado a esta carrera.
      $group_memberships = \Drupal::service('group.membership_loader')->loadByUser($current_user);
     
      foreach ($group_memberships as $membership) {
        
        
        $group = $membership->getGroup();
        \Drupal::messenger()->addMessage('HOOK29384kjklj ' . $group->getEntityTypeId() );
        // Verificar que el grupo esté relacionado con la universidad de la carrera actual.
        if (($group->getEntityTypeId() === 'node' || $group->getEntityTypeId() === 'group' ) && $group->getGroupType()->id() === 'universitytypegroup') {
       
          // Verificar si el usuario tiene el rol de Degree Admin dentro de este grupo.
          //\Drupal::messenger()->addMessage('HOOK ' . print_r($membership));
          $roles = $membership->getRoles();
          foreach ($roles as $role) {
            if ($role->id() === 'universitytypegroup-subject_admi') {
              // Desactivar el campo de universidad para Degree Admin.
              $form['field_carrera']['#disabled'] = TRUE;
              \Drupal::messenger()->addMessage('El campo Degree está desactivado para Degree Admin.');
              break 2; // Salir de ambos bucles.
            }
          }
            /*
            $form['field_universidad']['widget'][0]['target_id']['#default_value'] = $entity;
            $form['field_universidad']['widget'][0]['target_id']['#options'] = [$entity->id() => $entity->label()];
            $form['field_universidad']['widget'][0]['target_id']['#disabled'] = TRUE;
            */

          
        }
      }
    }
  }




}
