<?php

/**
 * @file
 * DACEM Footer module.
 */


/**
 * Implements hook_theme().
 */
function dacem_footer_theme($existing, $type, $theme, $path) {
  return [
    'dacem_footer_block' => [
      'variables' => [
        'institution'   => NULL,
        'primary_color' => NULL,
        'last_updated'  => NULL,
        'owner' => NULL,
        'nodebundle'    => NULL,
        'feedback_form' => NULL,
      ],
      'template' => 'dacem-footer-block',
    ],
  ];
}
