<?php



/**
 * Implements hook_preprocess_block() to add a button to the local actions block.
 */
function create_user_group_preprocess_block(&$variables) {
  

  
  if ($variables['plugin_id'] == 'local_actions_block') {
  

    $route_name = \Drupal::routeMatch()->getRouteName();
   
    if (strpos($route_name, 'view.group_members') !== false) {
    

      
      if (isset($variables['content']['group.add_member'])) {
   
      }
     
      $group = \Drupal::routeMatch()->getParameter('group');
      if ($group) {
     
        $current_user = \Drupal::currentUser();
        $membership = $group->getMember($current_user);

        if ($membership) {
  
          $roles = array_map(function ($role) {
            return $role->id();
          }, $membership->getRoles());

        

          if (in_array('universitytypegroup-university_a', $roles)) {
          
            $button_html = '<li><a href="/group/' . $group->id() . '/create-user" class="button button-action">Create user</a></li>';

         
            if (isset($variables['content']['#markup'])) {
            
              $variables['content']['#markup'] .= $button_html;
          
            } else {
             
              $variables['content']['#markup'] = $button_html;
              
            }
          }
        } else {
          
        }
      } else {
        
      }
    }
  }

}








