<?php

use Drupal\Core\Language\LanguageInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;

/**
 * @file
 * B5 subtheme theme file.
 */


use Drupal\Core\Language\LanguageManagerInterface;



/**
 * Implements hook_theme_suggestions_HOOK_alter() to provide custom templates.
 */
function b5subtheme_theme_suggestions_HOOK_alter(array &$suggestions, array $variables)
{
  // Your custom theme suggestions code.
}




/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function b5subtheme_preprocess_block(&$variables)
{
  // Your custom preprocess code for blocks.
}






function getEntityFromAlias($alias, $langcode = NULL)
{
  // Obtener el servicio de alias
  $alias_manager = \Drupal::service('path_alias.manager');

  // Obtener el path interno a partir del alias en el idioma solicitado
  $internal_path = $alias_manager->getPathByAlias('/' . $alias, $langcode);

  if (preg_match('/^\/node\/(\d+)$/', $internal_path, $matches)) {
    $nid = (int) $matches[1];

    // Cargar y retornar el nodo
    $node = Node::load($nid);

    // Si hay un idioma definido y el nodo tiene traducción, cargarla
    if ($langcode && $node->hasTranslation($langcode)) {
      return $node->getTranslation($langcode);
    }

    return $node;
  }

  return NULL;
}








/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function b5subtheme_preprocess_page(&$variables)
{



  




  // Your custom preprocess code for pages.
  $variables['#attached']['library'][] = 'b5subtheme/course_buttons';
  $path = \Drupal::theme()->getActiveTheme()->getPath() . '/translations/translations.yml';


  // Cargar el contenido del archivo YAML.
  if (file_exists($path)) {
    $translations = \Drupal\Component\Serialization\Yaml::decode(file_get_contents($path));

    // Verifica si las traducciones se están cargando correctamente.
    \Drupal::logger('b5subtheme')->notice('Translations loaded: <pre>@translations</pre>', ['@translations' => print_r($translations, TRUE)]);

    // Pasar las traducciones al contexto de Twig.
    $variables['translations'] = $translations;
  } else {
    \Drupal::logger('b5subtheme')->error('Translations file not found at path: @path', ['@path' => $path]);
  }

}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function b5subtheme_preprocess_node(&$variables)
{
  // Your custom preprocess code for nodes.
}

/**
 * Implements hook_preprocess_HOOK() for your custom templates.
 */
function b5subtheme_preprocess_HOOK(&$variables)
{
  // Your custom preprocess code for your custom templates.
}




/**
 * Implements hook_preprocess_HOOK() for views_view templates.
 */
function b5subtheme_preprocess_views_view(&$variables)
{

  // Importar el language_manager.
  $language_manager = \Drupal::service('language_manager');
  $variables['language_manager'] = $language_manager;

  //dump($variables['view']->id());

  $path = \Drupal::theme()->getActiveTheme()->getPath() . '/translations/translations.yml';

  // Cargar el contenido del archivo YAML.
  if (file_exists($path)) {
    $translations = \Drupal\Component\Serialization\Yaml::decode(file_get_contents($path));

    // Verifica si las traducciones se están cargando correctamente.
    \Drupal::logger('b5subtheme')->notice('Translations loaded: <pre>@translations</pre>', ['@translations' => print_r($translations, TRUE)]);

    // Pasar las traducciones al contexto de Twig.
    $variables['translations'] = $translations;
  } else {
    \Drupal::logger('b5subtheme')->error('Translations file not found at path: @path', ['@path' => $path]);
  }




  if ($variables['view']->id() == 'main_page') {
    $current_language = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
    $translated_institution = null;
    foreach ($variables['view']->result as $key => $row) {
     
      $institution = $row->_entity;


      if ($institution->hasTranslation($current_language)) {

        // Si la asignatura tiene traducción al idioma actual.
        $translated_institution = $institution->getTranslation($current_language);
        //$row->custom_url = $translated_subject->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($current_language)])->toString();


        $translated_url = $translated_institution->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($current_language)])->toString();

        // Extraer el idioma desde la URL original
        //$language_prefix = '/' . \Drupal::languageManager()->getCurrentLanguage()->getId();

        // Eliminar el prefijo del idioma si ya está presente en la URL original
        if (strpos($translated_url, '/' . $current_language) === 0) {

          $translated_url = substr($translated_url, strlen('/' . $current_language));

        }
        //dump($current_language . '/catalogue' . $translated_url);
        // Construir la nueva URL con el formato correcto
        $row->custom_url = $current_language . '/general-information' . $translated_url;
        $variables['view']->result[$key]->_entity = $translated_institution;

      } else {
        // Si no tiene traducción, usar el idioma original de la asignatura.
        $original_language = $institution->language()->getId();

        //$row->custom_url = $subject->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($original_language)])->toString();
        $translated_url = $institution->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($original_language)])->toString();

        // Extraer el idioma desde la URL original
        $language_prefix = \Drupal::languageManager()->getCurrentLanguage()->getId();

        // Eliminar el prefijo del idioma si ya está presente en la URL original
        if (strpos($translated_url, '/' . $original_language) === 0) {

          $translated_url = substr($translated_url, strlen('/' . $original_language));
        }

        // Construir la nueva URL con el formato correcto
        $row->custom_url = $language_prefix . '/general-information' . $translated_url;

        $variables['view']->result[$key]->_entity = $institution;
      }

      // Asignar la universidad traducida y la URL personalizada


    }
  }







  if ($variables['view']->id() == 'institution_catalogue') {
    $current_language = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();

    $grouped_carreras = [];



    foreach ($variables['view']->result as $row) {


      // Accede a las carreras relacionadas desde la relación inversa.
      if (isset($row->_relationship_entities['reverse__node__field_programme_institution'])) {

        $carrera = $row->_relationship_entities['reverse__node__field_programme_institution'];


        if ($carrera->hasTranslation($current_language)) {
          $carrera_translated = $carrera->getTranslation($current_language);
        } else {
          $carrera_translated = $carrera; // Usa la carrera en su idioma original.
        }

        // Accede a la universidad principal.
        $institution = $row->_entity;


        // Obtener el alias del programa en el idioma actual
        $programme_alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $carrera_translated->id(), $current_language);

        // Obtener el código del idioma actual
        $language_prefix = '/' . \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();

        // Construir la URL con el formato deseado
        $url = $language_prefix . '/catalogue/' . trim($programme_alias, '/');


        // Valida si la entidad tiene un ID válido.
        if ($carrera_translated && $carrera_translated->id()) {
          // Obtén el área para agrupar las carreras.
          $area = $carrera_translated->get('field_programme_area')->value ?? 'undefined';
          \Drupal::logger('custom_log')->notice('Area--> ' . $area);

          //dump('/catalogue' . $carrera_translated->toUrl()->toString());
          $grouped_carreras[$area][] = [
            'title' => $carrera_translated->getTitle(),
            'url' => $url,


          ];
        }
      }
    }

    // Ordena las carreras alfabéticamente dentro de cada área.
    foreach ($grouped_carreras as &$carreras) {
      usort($carreras, function ($a, $b) {
        return strcmp($a['title'], $b['title']);
      });
    }

    // Pasa las carreras agrupadas a la plantilla.
    $variables['grouped_carreras'] = $grouped_carreras;
  }



  if ($variables['view']->id() === 'programme_information') {

    foreach ($variables['view']->result as &$row) {

      // Asegúrate de que estamos procesando asignaturas relacionadas.
      if (!empty($row->_relationship_entities['reverse__node__field_iec_programme'])) {

        $iec = $row->_relationship_entities['reverse__node__field_iec_programme'];

        if ($iec instanceof Node) {



          $current_language = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();

          if ($iec->hasTranslation($current_language)) {

            // Si la asignatura tiene traducción al idioma actual.
            $translated_iec = $iec->getTranslation($current_language);
            //$row->custom_url = $translated_subject->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($current_language)])->toString();


            $translated_url = $translated_iec->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($current_language)])->toString();

            // Extraer el idioma desde la URL original
            //$language_prefix = '/' . \Drupal::languageManager()->getCurrentLanguage()->getId();

            // Eliminar el prefijo del idioma si ya está presente en la URL original
            if (strpos($translated_url, '/' . $current_language) === 0) {

              $translated_url = substr($translated_url, strlen('/' . $current_language));

            }
            //dump($current_language . '/catalogue' . $translated_url);
            // Construir la nueva URL con el formato correcto
            $row->custom_url = $current_language . '/catalogue' . $translated_url;


          } else {
            // Si no tiene traducción, usar el idioma original de la asignatura.
            $original_language = $iec->language()->getId();
            //$row->custom_url = $subject->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($original_language)])->toString();
            $translated_url = $translated_iec->toUrl('canonical', ['language' => \Drupal::languageManager()->getLanguage($original_language)])->toString();

            // Extraer el idioma desde la URL original
            $language_prefix = \Drupal::languageManager()->getCurrentLanguage()->getId();

            // Eliminar el prefijo del idioma si ya está presente en la URL original
            if (strpos($translated_url, '/' . $original_language) === 0) {

              $translated_url = substr($translated_url, strlen('/' . $original_language));
            }

            // Construir la nueva URL con el formato correcto
            $row->custom_url = $language_prefix . '/catalogue' . $translated_url;


          }
        }
      }
    }
  }






// Verifica si estamos en la ruta deseada.
if (\Drupal::routeMatch()->getRouteName() === 'view.general_information.page_1') {
  // Obtén el idioma actual.
  $current_language = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
  // Obtén el nodo pasado como argumento a la vista.
  $arg_0 = \Drupal::routeMatch()->getParameter('arg_0');

  if ($arg_0 && is_numeric($arg_0)) {

    $node = \Drupal\node\Entity\Node::load($arg_0);
  } else {

    $node = getEntityFromAlias($arg_0, $current_language);
  }


  if ($node && $node->hasTranslation($current_language)) {

    // Carga la traducción activa del nodo.
    $translated_node = $node->getTranslation($current_language);
    // Pasa el nodo traducido a las plantillas Twig.
    //dump($translated_node);
    $variables['university'] = $translated_node;

    // Obtener los campus asociados a la universidad.
    $campuses = \Drupal::entityTypeManager()
      ->getStorage('node')
      ->loadByProperties([
        'type' => 'campus', // Asegúrate de que 'campus' sea el tipo de contenido.
        'field_campus_institution' => $translated_node->id(),
      ]);
      

    // Traducir los campus al idioma actual.
    $translated_campuses = [];
    foreach ($campuses as $campus) {
      if ($campus->hasTranslation($current_language)) {
        $translated_campuses[] = $campus->getTranslation($current_language);
      } else {
        $translated_campuses[] = $campus;
      }
    }
    // Verifica si hay campus disponibles.


    


  }
  $variables['campuses'] = !empty($translated_campuses) ? array_values($translated_campuses) : NULL;

}







  if ($variables['view']->id() == 'resources_and_services') {
    $current_language = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
    $variables['current_language'] = $current_language;

    $arg_0 = \Drupal::routeMatch()->getParameter('arg_0');
    if ($arg_0 && is_numeric($arg_0)) {

      $node = \Drupal\node\Entity\Node::load($arg_0);
    } else {
  
      $node = getEntityFromAlias($arg_0, $current_language);
    }
  
  
    if ($node && $node->hasTranslation($current_language)) {
  
      // Carga la traducción activa del nodo.
      $translated_node = $node->getTranslation($current_language);
      // Pasa el nodo traducido a las plantillas Twig.
      //dump($translated_node);
      $variables['university'] = $translated_node;
  
      // Obtener los campus asociados a la universidad.
      $campuses = \Drupal::entityTypeManager()
        ->getStorage('node')
        ->loadByProperties([
          'type' => 'campus', // Asegúrate de que 'campus' sea el tipo de contenido.
          'field_campus_institution' => $translated_node->id(),
        ]);
        
  
      // Traducir los campus al idioma actual.
      $translated_campuses = [];
      foreach ($campuses as $campus) {
        if ($campus->hasTranslation($current_language)) {
          $translated_campuses[] = $campus->getTranslation($current_language);
        } else {
          $translated_campuses[] = $campus;
        }
      }
      // Verifica si hay campus disponibles.
  
     
      
  
  
    }
    $variables['campuses'] = !empty($translated_campuses) ? array_values($translated_campuses) : NULL;

  }

}


