<?php

use Drupal\node\Entity\Node;
/**
 * Implements hook_theme().
 */
function admin_area_theme($existing, $type, $theme, $path) {
    return [
      'admin-area' => [
        'variables' => ['data' => NULL],
        // Usamos el servicio de extensión para obtener la ruta del tema.
        'path' => \Drupal::service('extension.list.theme')->getPath('b5subtheme') . '/templates',
      ],
    ];
  }
  
/**
 * Implements hook_entity_access().
 */
function admin_area_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
  // Solo manejamos nodos.
  if ($entity->getEntityTypeId() !== 'node') {
    return \Drupal\Core\Access\AccessResult::neutral();
  }

  // Verifica que es una asignatura.
  if ($entity->bundle() === 'individual_educational_component') {
    // Carga los grupos del usuario.
    $groups = \Drupal::service('group.membership_loader')->loadByUser($account);

    foreach ($groups as $membership) {
      $group = $membership->getGroup();
      $roles = $membership->getRoles();

      // Verifica si el usuario tiene un rol válido en este grupo.
      foreach ($roles as $role) {
        if (in_array($role->id(), ['universitytypegroup-university_a', 'universitytypegroup-degree_admin', 'universitytypegroup-subject_admi'])) {
          // Verifica permisos del rol del grupo.
          if ($role->id() === 'universitytypegroup-university_a' && in_array($operation, ['translate', 'view'])) {
            return \Drupal\Core\Access\AccessResult::allowed();
          }
          if ($role->id() === 'universitytypegroup-degree_admin' && in_array($operation, ['translate'])) {
            return \Drupal\Core\Access\AccessResult::allowed();
          }
          if ($role->id() === 'universitytypegroup-subject_admi' && in_array($operation, ['translate'])) {
            return \Drupal\Core\Access\AccessResult::allowed();
          }
        }
      }
    }
  }

  // Devuelve acceso neutral si no se cumple ninguna condición.
  return \Drupal\Core\Access\AccessResult::neutral();
}

 /* Implementación de hook_form_alter().
 */


function admin_area_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //\Drupal::logger('admin_area')->info('Interceptado formulario con ID: @form_id', ['@form_id' => $form_id]);





  // Comprobar si estamos en un formulario de vista expuesta.
  if ($form_id == 'views_exposed_form') {
    \Drupal::logger('admin_area')->info('Estamos en formulario de view exposed form');

    // Imprimir la estructura completa del formulario en el log.
    //\Drupal::logger('admin_area')->info('<pre>@form</pre>', ['@form' => print_r($form, TRUE)]);
  }


    if($form_id != 'views_exposed_form' && $form_id != 'search_block_form'){
    \Drupal::logger('admin_area_2')->info('Interceptado formulario con ID: @form_id', ['@form_id' => $form_id]);
  }
  

  if($form_id == 'node_institution_edit_form' || $form_id == 'node_programme_edit_form' || $form_id == 'node_individual_educational_component_edit_form' || 
    $form_id == 'node_institution_form' || $form_id == 'node_programme_form' || $form_id == 'node_individual_educational_component_form' || $form_id == 'node_campus_edit_form' ||
    $form_id == 'node_campus_form' || $form_id == 'node_resources_and_services_edit_form' || $form_id == 'node_resources_and_services_form' || $form_id == 'node_organizational_unit_edit_form'
    || $form_id == 'node_organizational_unit_form' || $form_id == 'node_academic_authority_edit_form' || $form_id == 'node_academic_authority_form'){
    \Drupal::logger('admin_area_2')->info('Dentro do if node edit formmmmm');
    \Drupal::logger('admin_area_2')->info('ACADEMIC AUTHORITYYYYY');
    $form['actions']['submit']['#submit'][] = 'admin_area_redirect_after_translation';
  }


  
  if ($form_id === 'content_translation_overview_add_form') {
    \Drupal::logger('admin_area')->info('Formulario de traducción interceptado.');

    $node = $form_state->getFormObject()->getEntity();
    if ($node) {
      \Drupal::logger('admin_area')->info('Nodo cargado para traducción: ID: @id, tipo: @type', [
        '@id' => $node->id(),
        '@type' => $node->bundle(),
      ]);
    } else {
      \Drupal::logger('admin_area')->error('No se pudo cargar el nodo para el formulario de traducción.');
    }
  }



  $entity_types = ['programme', 'institution', 'resources_and_services', 'individual_educational_component', 'campus', 'organizational_unit', 'academic_authority'];

  // Verifica si el formulario pertenece a la creación o edición de estas entidades.
  foreach ($entity_types as $type) {
    if ($form_id === "node_{$type}_form" || $form_id === "node_{$type}_edit_form" || $form_id == 'create_user_in_group_form') {

      // Obtener la URL de la página anterior.
      $request = \Drupal::requestStack()->getCurrentRequest();
      $referer = $request->headers->get('referer');

      // Si no hay referer, redirigir a /my-area por defecto.
      $cancel_url = $referer ?: '/';
      
      // Agregar un botón "Cancel".
      $form['actions']['cancel'] = [
        '#type' => 'button',
        '#value' => t('Cancel'),
        '#attributes' => ['onclick' => 'window.location.href="' . $cancel_url . '"; return false;'],
      ];

      if (isset($form['actions']['preview'])) {
        unset($form['actions']['preview']);
      }


    

      break; // Salir del bucle una vez que se encuentra un tipo coincidente.
    }
  }





}



/**
 * Callback para redirigir después de guardar una traducción.
 */
function admin_area_redirect_after_translation(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  $current_user = \Drupal::currentUser();
  $user = \Drupal\user\Entity\User::load($current_user->id());

  \Drupal::logger('admin_area')->info('Redirect after translatioooooonnn');

  if ($node && $user) {
    $memberships = \Drupal::service('group.membership_loader')->loadByUser($user);
    if (!empty($memberships)) {
      $group = reset($memberships)->getGroup();

      // Obtener tipo de entidad y rol del grupo
      $entity_type = $node->bundle(); // 'programme', 'iec', etc.
      $role = null;
      $membership = \Drupal::service('group.membership_loader')->load($group, $user);
      if ($membership) {
        foreach ($membership->getRoles() as $r) {
          switch ($r->id()) {
            case 'universitytypegroup-university_a':
              $role = 'university_admin'; break;
            case 'universitytypegroup-degree_admin':
              $role = 'programme_admin'; break;
            case 'universitytypegroup-subject_admi':
              $role = 'iec_admin'; break;
          }
        }
      }

      // Mapear ruta
      $route_maps = [
        'programme' => [
          'university_admin' => 'view.admin_programmes.page_1',
          'programme_admin'  => 'view.admin_programmes.page_2',
        ],
        'iec' => [
          'university_admin' => 'view.admin_iecs.page_1',
          'programme_admin'  => 'view.admin_iecs.page_2',
          'iec_admin'        => 'view.admin_iecs.page_3',
        ],
        'campus' => [
          'university_admin' => 'view.admin_campuses.page_1',
        ],
        'rs' => [
          'university_admin' => 'view.admin_rs.page_1',
        ],
        'institution' => [
          'university_admin' => 'view.admin_institution.page_1',
        ],
        'organizational_unit' => [
          'university_admin' => 'view.admin_organizational_units.page_1',
        ],
        'academic_authority' => [
          'university_admin' => 'view.admin_academic_authorities.page_1',
        ],
        
      ];

      if (isset($route_maps[$entity_type][$role])) {
        $form_state->setRedirect($route_maps[$entity_type][$role]);
        return;
      }
    }
  }

  // Redirección por defecto si no encuentra grupo o rol
  $form_state->setRedirect('<front>');
}



/**
 * Implements hook_page_top().
 */
function admin_area_page_top(array &$page_top) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  if ($route_name == 'entity.node.content_translation_overview') {

    /*
    // Crear el botón "Go to My Area".
    $url = \Drupal\Core\Url::fromUserInput('/my-area');

    $button = [
      '#type' => 'link',
      '#title' => t('Go to My Area'),
      '#url' => $url,
      '#attributes' => [
        'class' => ['btn', 'btn-primary', 'mb-3'],
        'style' => 'margin-bottom: 10px;',
      ],
    ];

    // Obtener la URL de la página anterior.
    $request = \Drupal::requestStack()->getCurrentRequest();
    $referer = $request->headers->get('referer');

    // Si no hay referer, redirigir a /my-area por defecto.
    $cancel_url = $referer ?: '/my-area';

    // Agregar un botón "Cancel".
    $button_cancel = [
      '#type' => 'button',
      '#value' => t('Cancel'),
      '#attributes' => ['onclick' => 'window.location.href="' . $cancel_url . '"; return false;',
      'class' => ['btn', 'btn-secondary', 'mb-3'],
      'style' => 'margin-bottom: 10px;', 'color'],
    ];


    

    // Añadir el botón al array renderizable de la página.
    $page_top['go_to_my_area_button'] = $button;
    $page_top['cancel'] = $button_cancel;
  
  */
    }
    
}





/**
 * Implements hook_form_FORM_ID_alter().
 */
function admin_area_form_group_node_individual_educational_component_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $programme_id = \Drupal::request()->query->get('field_iec_programme');

  if ($programme_id && is_numeric($programme_id)) {
    $programme = Node::load($programme_id);

    if ($programme && $programme->bundle() === 'programme') {
      $form['field_iec_programme']['#default_value'] = [$programme];
      $form['field_iec_programme']['#disabled'] = TRUE;
    }
  }
}




/**use Drupal\node\Entity\Node;

use Drupal\node\Entity\Node;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function admin_area_form_node_programme_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $institution_id = \Drupal::request()->query->get('field_programme_institution');

  if ($institution_id && is_numeric($institution_id)) {
    $institution = Node::load($institution_id);

    if ($institution && $institution->bundle() === 'institution') {
      // Esta es la forma correcta con entity_autocomplete
      $form['field_programme_institution']['widget'][0]['target_id']['#default_value'] = $institution;

      // Bloquearlo para que no sea editable
      $form['field_programme_institution']['widget'][0]['target_id']['#disabled'] = TRUE;
    }
  }
}


function admin_area_form_node_individual_educational_component_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $programme_id = \Drupal::request()->query->get('field_iec_programme');

  if ($programme_id && is_numeric($programme_id)) {
    $programme = Node::load($programme_id);

    if ($programme && $programme->bundle() === 'programme') {
      // Esta es la forma correcta con entity_autocomplete
      $form['field_iec_programme']['widget'][0]['target_id']['#default_value'] = $programme;

      // Bloquearlo para que no sea editable
      $form['field_iec_programme']['widget'][0]['target_id']['#disabled'] = TRUE;
    }
  }
}



function admin_area_form_node_campus_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $campus_id = \Drupal::request()->query->get('field_campus_institution');

  if ($campus_id && is_numeric($campus_id)) {
    $campus = Node::load($campus_id);

    if ($campus && $campus->bundle() === 'campus') {
      // Esta es la forma correcta con entity_autocomplete
      $form['field_campus_institution']['widget'][0]['target_id']['#default_value'] = $campus;

      // Bloquearlo para que no sea editable
      $form['field_campus_institution']['widget'][0]['target_id']['#disabled'] = TRUE;
    }
  }
}




function admin_area_form_node_organizational_unit_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $institution_id = \Drupal::request()->query->get('field_ou_institution');

  if ($institution_id && is_numeric($institution_id)) {
    $institution = Node::load($institution_id);

    if ($institution && $institution->bundle() === 'institution') {
      // Esta es la forma correcta con entity_autocomplete
      $form['field_ou_institution']['widget'][0]['target_id']['#default_value'] = $institution;

      // Bloquearlo para que no sea editable
      $form['field_ou_institution']['widget'][0]['target_id']['#disabled'] = TRUE;
    }
  }
}




function admin_area_form_node_programme_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
    $form['field_programme_ou']['#disabled'] = TRUE;
  
}
